services:
  # database:
  #   image: postgres:15
  #   container_name: postgres_db
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_DB: bruba
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${Sa_Password:-password123} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "kBc6yG77zbjelv"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    image: bruba-api:latest
    container_name: nestjs_app
    environment:
      DATABASE_URL: postgresql://postgres:admin@database:5432/bruba?schema=public
      NODE_ENV: production
    ports:
      - "3000:3000"
    command: [ "sh", "-c", "npx prisma generate && npx prisma migrate deploy && node dist/src/main" ]
    
volumes:
  sqlserver_data:
