services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bruba
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: bruba-api:latest
    container_name: nestjs_app
    environment:
      DATABASE_URL: postgresql://postgres:admin@database:5432/bruba?schema=public
      NODE_ENV: production
    ports:
      - "3000:3000"
    command: [ "sh", "-c", "npx prisma generate && npx prisma migrate deploy && node dist/src/main" ]
    
volumes:
  db_data:
